[versions]
agp = "8.4.1"
coil-compose = "2.5.0"
kotlin = "2.0.0"
activity-compose = "1.9.0"
compose-plugin = "1.6.10"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

